[package]
name = "astcenc"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "astcenc"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
image = "0.25.2"
webp = "0.3.0"
libwebp-sys = "0.9.5"